CREATE TABLE FLIGHT(
  FLIGHTNO CHAR(5),
  FLIGHTNAME VARCHAR(255),
  ORIGIN VARCHAR(255),
  DESTINATION  VARCHAR(255),
  DEP_DATE DATE,
  DEP_TIME VARCHAR(8),
  PRIMARY KEY(FLIGHTNO)
);

CREATE TABLE PILOT_DETAILS(
  P_ID CHAR(5),
  NAME VARCHAR(255),
  FLIGHTNO CHAR(5),
  FLYHRS FLOAT,
  PRIMARY KEY(P_ID),
  FOREIGN KEY (FLIGHTNO) REFERENCES FLIGHT(FLIGHTNO)
);

INSERT INTO FLIGHT VALUES
('CD0','INDIGO','SURAT','DONGGUAN','2022-05-14','02:20'),
('CD1','AIR INDIA','KATHMANDU','PHNOM PENH','2022-05-17','05:40'),
('CC2','SPICEJET','MINSK','LUSAKA','2022-05-30','06:00'),
('CC3','GO FIRST','NEW TAIPEI CITY','SHIJIAZHUANG','2022-05-27','06:20'),
('CE4','AIRASIA INDIA','OSAKA','PORTO ALEGRE','2022-05-13','07:40'),
('CC5','VISTARA','BANGALORE','DAR ES SALAAM','2022-05-09','13:20'),
('CE6','ALLIANCE AIR','ALEXANDRIA','SHIRAZ','2022-05-29','13:40'),
('CC7','TRUJET','MANDALAY','LUANDA','2022-05-20','20:20'),
('CE8','BANGKOK AIRWAYS','NOVOSIBIRSK','SEMARANG','2022-05-19','20:40'),
('CD9','BRITISH AIRWAYS','CHENNAI','OUAGADOUGOU','2022-05-10','21:20')
;

INSERT INTO PILOT_DETAILS VALUES
('PMO0','THEODORE','CD0',15),
('PMA1','RONALD','CD1',11),
('PMA5','ERNESTO','CC5',17),
('PMA9','MARC','CD9',11),
('PMO7','ALSTONE','CC7',20),
('PFA2','AMANDA','CC2',10),
('PFO3','LESLIE','CC3',12),
('PFA4','TERESA','CE4',18),
('PFO6','SHEILA','CE6',17),
('PFO8','MAY','CE8',18)
;

ALTER TABLE PILOT_DETAILS
ADD P_AGE INTEGER;

ALTER TABLE PILOT_DETAILS
ADD P_GENDER CHAR(1);

UPDATE PILOT_DETAILS
SET P_GENDER = 'M'
WHERE P_ID LIKE 'PM%';

UPDATE PILOT_DETAILS
SET P_GENDER = 'F'
WHERE P_ID LIKE 'PF%';

UPDATE PILOT_DETAILS
SET P_AGE = 35
WHERE P_ID LIKE '%O%';

UPDATE PILOT_DETAILS
SET P_AGE = 40
WHERE P_ID LIKE '%A%';

SELECT * FROM FLIGHT;

SELECT FLIGHTNO,FLIGHTNAME FROM FLIGHT 
WHERE ORIGIN = 'BANGALORE';

SELECT DEP_DATE,DEP_TIME FROM FLIGHT;

UPDATE PILOT_DETAILS
SET FLYHRS = FLYHRS + 10
WHERE FLIGHTNO LIKE '%C%';

UPDATE PILOT_DETAILS
SET FLYHRS = FLYHRS + 15
WHERE FLIGHTNO LIKE '%D%';

UPDATE PILOT_DETAILS
SET FLYHRS = FLYHRS + 20
WHERE FLIGHTNO LIKE '%E%';

SELECT * from PILOT_DETAILS where FLYHRS IN (
  SELECT FLYHRS FROM PILOT_DETAILS
  GROUP BY FLYHRS HAVING COUNT(*) > 1
);

DELETE FROM PILOT_DETAILS
WHERE P_ID = 'PFA2';

SELECT * FROM PILOT_DETAILS;

SELECT * FROM FLIGHT;